name: Java CI

on:
  push:
  pull_request:
  schedule: [ cron: '21 1 * * 5' ] # weekly: At 01:21 on Friday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - run: mvn --batch-mode --show-version --no-transfer-progress -DCI=GitHub install
